### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by mattbasta** [diegoalejogm/gans#1]
Hi there. I'm very interested in creating GANs but have been unable to find much information, so I was hoping you could help answer somethings. Just a couple quick questions.

1. For your TF implementation, you didn't use `tf.contrib.gan`. Can you briefly talk about why? Is it too restrictive?
2. If, instead of training on and generating images, you wanted to create a GAN that trained on and generated a few dozen floating point numbers, how would that be accomplished? Is it simply a matter of changing the shape of the input to the discriminator, changing `IMAGE_SIZE` to be the number of floats, and supplying appropriate training data (from, say, a CSV)?

Thanks very much, your time is appreciated!

**Comment by diegoalejogm** [comment]
Sorry for the delay here,

@mattbasta :
1. I wanted to create GANs from scratch, in order to be very clear on how they worked. I understand that `tf.contrib.gan_` is an API that does implement GANs but hides all the technical details.

2. Yes, that's exactly what you would do. Take into account that a 1D array must be the output, such as in the Vanilla GAN notebooks. If you use DC GAN, a 2D vector output will result, and it may not make sense for your purpose.

Hope I've responded to all your doubts successfully.
