### ISSUE TITLE
ImportError: cannot import name 'Logger' environment versions issue?

### ISSUE THREAD

**Issue by aspiringguru** [diegoalejogm/gans#2]
any ideas?

from utils import Logger
ImportError: cannot import name 'Logger'

utils==0.9.0
$ python --version
Python 3.6.4 :: Anaconda, Inc.

**Comment by diegoalejogm** [comment]
What notebook were you executing?

**Comment by diegoalejogm** [comment]
hi @aspiringguru 

The problem here is that the `Logger` class we use  is found in the utils.py file [in this same repository](https://github.com/diegoalejogm/gans/blob/master/utils.py), and you might have installed a different `utils` package [from PIP](https://pypi.org/project/utils/). 

You could either __1)__ uninstall the `utils` package from your environment with `pip uninstall utils`, or __2)__ rename the `utils.py` file in this repo to something different (say `foo`) and importing Logger as required (e.g. `from foo import Logger`).

Let me know if that works.

**Comment by yashsingla984** [comment]
Hey Diego,

I have been facing problem with from utils import Logger.I am using tensorflow 2.0 and I have been facing problem with the code use have made of Vanilla Gan in tensorflow.
